/*
 * Audit Log Action Constants
 */
export const AUDIT_ACTIONS = {
  USER_LOGIN: "USER_LOGIN",
  PATIENT_CREATE: "PATIENT_CREATE",
  PATIENT_EDIT: "PATIENT_EDIT",
  APPOINTMENT_CREATE: "APPOINTMENT_CREATE",
  CONSULTATION_CREATE: "CONSULTATION_CREATE",
  PRESCRIPTION_CREATE: "PRESCRIPTION_CREATE",
  LAB_RESULT_PUBLISH: "LAB_RESULT_PUBLISH",
  INVOICE_CREATE: "INVOICE_CREATE",
  PAYMENT_RECORD: "PAYMENT_RECORD",
  DISPENSE_MEDICATION: "DISPENSE_MEDICATION",
  STOCK_UPDATE: "STOCK_UPDATE",
  STAFF_CREATE: "STAFF_CREATE",
  ADMISSION_CREATE: "ADMISSION_CREATE",
  DISCHARGE_COMPLETE: "DISCHARGE_COMPLETE",
};

/*
 * Roles
 */
export const ROLES = {
  SUPER_ADMIN: "SuperAdmin",
  HOSPITAL_ADMIN: "HospitalAdmin",
  RECEPTIONIST: "Receptionist",
  DOCTOR: "Doctor",
  NURSE: "Nurse",
  LAB_TECH: "LabTechnician",
  PHARMACIST: "Pharmacist",
  BILLING_OFFICER: "BillingOfficer",
  INVENTORY_OFFICER: "InventoryOfficer",
};

/*
 * Statuses
 */
export const STATUSES = {
  ACTIVE: "active",
  INACTIVE: "inactive",
  SUSPENDED: "suspended",
};
